image: mcr.microsoft.com/dotnet/sdk:latest

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - dotnet restore
    - dotnet build --configuration Release

  only:
    - dev

deploy:
  stage: deploy
  script:
    - apt-get update && apt-get install -y sshpass
    - dotnet publish --configuration Release --property:PublishDir=./publish
    - sshpass -p "$DEPLOY_PASS" scp -P 3456 -o StrictHostKeyChecking=no -r ./publish/* gitlabdeployer@$DEPLOY_IP:/projects/tmyscan/indexer/
    - sshpass -p "$DEPLOY_PASS" ssh -p 3456 -o StrictHostKeyChecking=no gitlabdeployer@$DEPLOY_IP 'sudo systemctl restart Indexer.service'
  only:
    - master